### ISSUE TITLE
emdloss compilation bug

### ISSUE THREAD

**Issue by whuhxb** [ZhanHeshen/PointCMT#4]
Hi @yanx27 @ZhanHeshen 

I use the environment you listed in PointCMT (cuda10.1, pytorch 1.4.0), and try to compile the emdloss, but the bugs occured as follow. How to solve?

Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    'build_ext': BuildExtension
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 372, in build_extensions
    build_ext.build_extensions(self)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 556, in build_extension
    depends=ext.depends,
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/setuptools/_distutils/ccompiler.py", line 599, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 288, in unix_wrap_compile
    "'-fPIC'"] + cflags + _get_cuda_arch_flags(cflags)
  File "/export/home/hanxiaobing/anaconda3/envs/pointcmt/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1027, in _get_cuda_arch_flags
    raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
ValueError: Unknown CUDA arch (8.0) or GPU not supported

**Comment by ZhanHeshen** [comment]
Hi, may I ask which kind of GPU you used?

**Comment by whuhxb** [comment]
> Hi, may I ask which kind of GPU you used?

Current, my GPU is Tesla V100  32G. Which kind of GPU should I use? Thanks.

**Comment by ZhanHeshen** [comment]
It meets the needed environment of PointCMT, I am not sure why you come across this issue. Maybe it related to the code of emd, this package is hard to install during my experiments too. I suggest you can find other implementations of emd distance or chamfer distance, they can also work.
